version: "3.9"

services:
  buildenv:
    build: ./docker
    container_name: buildroot-armv5
    volumes:
      - ./:/workspace
      - ./artifacts:/artifacts
    tty: true
    cpus: '2'
    cpu_shares: 256

